---
- name: Elasticsearch with custom configuration
  hosts: elastic01
  become: yes
  become_user: root
  roles:
    - { role: ansible-elasticsearch, es_instance_name: "elastic01",
    es_config: {
          network.host: "{{hostvars['elastic01'].ansible_eth1.ipv4.address}}"
      }
      } 
    - role: kibana
  vars:
    es_version: 2.3.1
    es_scripts: false
    es_plugins:
        - plugin: license
        - plugin: marvel-agent
